FROM alpine:3.21

ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates tzdata

COPY $TARGETPLATFORM/rhizome /usr/local/bin/rhizome
COPY $TARGETPLATFORM/rhizome-launcher /usr/local/bin/rhizome-launcher

ENTRYPOINT ["rhizome-launcher"]
CMD ["-console", "-public", "-no-browser"]
